### ISSUE TITLE
Unable to find entity

### ISSUE THREAD

**Issue by andrew-sumner** [mattybeard/DataExportValidationChecker#2]
Trying to validate metadata for calendar entity but cannot find it it the list. It doesn't help the the list of entities is unordered.

**Comment by mattybeard** [comment]
I'm only a year late commenting on your issue 👍 

The drop down for the entity list is the only part of the tool I didn't write - I'm actually using a control from this repo:
https://github.com/jamesnovak/xrmtb.XrmToolBox.Controls by the awesome @jamesnovak.

The sort order I think is in the logical or schema name, not the friendly name so I see your confusion but generally, my usage is to start typing and let it auto fill. Having said that, calender still isn't in there BUT I don't believe that is an entity you would want to find unless it's a custom entity called that.

Would love to know your use case, I'll close this for now but feel free to re-open.

PS 2.0 of this tool is due to launch in the next few days, so keep an eye out.
